### PR TITLE
List legacy types as “deprecated alias names” per RFC 6838 section 4.2.9

### PR DESCRIPTION
**Pull request by mathiasbynens**
This simplifies the document to just two registrations, each with a set of aliases.

- Under “Common JavaScript Media Types”: `text/javascript` and its aliases with file extensions `.js` and `.mjs`
- Under “Historic JavaScript Media Types”: `text/ecmascript` and its aliases with file extensions `.es` and `.mjs`

https://datatracker.ietf.org/doc/html/rfc6838#section-4.2.9

### CODE REVIEW

**Comment by annevk** [comment]
What's the difference between deprecated and obsolete?

**Comment by linuxwolf** [comment]
> What's the difference between deprecated and obsolete?

It's yak shaving to get this document published.  Practically there should be no difference.

**Comment by annevk** [comment]
So why not mark them all as deprecated aliases of text/javascript?

**Comment by mathiasbynens** [comment]
> So why not mark them all as deprecated aliases of `text/javascript`?

Because we don't want to link the `.es` extension to any new types.

**Comment by annevk** [comment]
I guess that's okay, though wouldn't it be preferable if a server started serving `.es` with `text/javascript` rather than `text/ecmascript`? If both extensions continue to exist anyway, might as well get people to align on the newer type for the ecosystem that doesn't care much about extensions.

**Comment by mathiasbynens** [comment]
I agree with you, @annevk, but I'm trying to avoid making any normative changes at this point (which might result in more pushback and IETF review rounds), especially when it's about something as insignificant as the `.es` extension which doesn't seem to matter very much in practice anyhow. The patch in its current form is (I think!) just a refactoring that was requested for simplification purposes.

**Comment by annevk** [comment]
Fair. Something to consider if we ever want to update this.

**Pull request merged**
